version: '3.8'

services:
  bot:
    build: .
    container_name: haberfoni_bot
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL:-mysql://haberfoni_user:Haberfoni_Secur3!DB@db:3306/haberfoni}
    networks:
      - app_network

    volumes:
      - ../public/uploads:/public/uploads
networks:
  app_network:
    name: haberfoni_network
    external: true
